# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bharanee/code/repos/c++/dbicpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bharanee/code/repos/c++/dbicpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bharanee/code/repos/c++/dbicpp/CMakeFiles /home/bharanee/code/repos/c++/dbicpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bharanee/code/repos/c++/dbicpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dbdmysql

# Build rule for target.
dbdmysql: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dbdmysql
.PHONY : dbdmysql

# fast build rule for target.
dbdmysql/fast:
	$(MAKE) -f CMakeFiles/dbdmysql.dir/build.make CMakeFiles/dbdmysql.dir/build
.PHONY : dbdmysql/fast

#=============================================================================
# Target rules for targets named dbdpg

# Build rule for target.
dbdpg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dbdpg
.PHONY : dbdpg

# fast build rule for target.
dbdpg/fast:
	$(MAKE) -f CMakeFiles/dbdpg.dir/build.make CMakeFiles/dbdpg.dir/build
.PHONY : dbdpg/fast

#=============================================================================
# Target rules for targets named dbic++

# Build rule for target.
dbic++: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dbic++
.PHONY : dbic++

# fast build rule for target.
dbic++/fast:
	$(MAKE) -f CMakeFiles/dbic++.dir/build.make CMakeFiles/dbic++.dir/build
.PHONY : dbic++/fast

#=============================================================================
# Target rules for targets named example

# Build rule for target.
example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example
.PHONY : example

# fast build rule for target.
example/fast:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/build
.PHONY : example/fast

src/container.o: src/container.cc.o
.PHONY : src/container.o

# target to build an object file
src/container.cc.o:
	$(MAKE) -f CMakeFiles/dbic++.dir/build.make CMakeFiles/dbic++.dir/src/container.cc.o
.PHONY : src/container.cc.o

src/container.i: src/container.cc.i
.PHONY : src/container.i

# target to preprocess a source file
src/container.cc.i:
	$(MAKE) -f CMakeFiles/dbic++.dir/build.make CMakeFiles/dbic++.dir/src/container.cc.i
.PHONY : src/container.cc.i

src/container.s: src/container.cc.s
.PHONY : src/container.s

# target to generate assembly for a file
src/container.cc.s:
	$(MAKE) -f CMakeFiles/dbic++.dir/build.make CMakeFiles/dbic++.dir/src/container.cc.s
.PHONY : src/container.cc.s

src/dbic++.o: src/dbic++.cc.o
.PHONY : src/dbic++.o

# target to build an object file
src/dbic++.cc.o:
	$(MAKE) -f CMakeFiles/dbic++.dir/build.make CMakeFiles/dbic++.dir/src/dbic++.cc.o
.PHONY : src/dbic++.cc.o

src/dbic++.i: src/dbic++.cc.i
.PHONY : src/dbic++.i

# target to preprocess a source file
src/dbic++.cc.i:
	$(MAKE) -f CMakeFiles/dbic++.dir/build.make CMakeFiles/dbic++.dir/src/dbic++.cc.i
.PHONY : src/dbic++.cc.i

src/dbic++.s: src/dbic++.cc.s
.PHONY : src/dbic++.s

# target to generate assembly for a file
src/dbic++.cc.s:
	$(MAKE) -f CMakeFiles/dbic++.dir/build.make CMakeFiles/dbic++.dir/src/dbic++.cc.s
.PHONY : src/dbic++.cc.s

src/drivers/mysql.o: src/drivers/mysql.cc.o
.PHONY : src/drivers/mysql.o

# target to build an object file
src/drivers/mysql.cc.o:
	$(MAKE) -f CMakeFiles/dbdmysql.dir/build.make CMakeFiles/dbdmysql.dir/src/drivers/mysql.cc.o
.PHONY : src/drivers/mysql.cc.o

src/drivers/mysql.i: src/drivers/mysql.cc.i
.PHONY : src/drivers/mysql.i

# target to preprocess a source file
src/drivers/mysql.cc.i:
	$(MAKE) -f CMakeFiles/dbdmysql.dir/build.make CMakeFiles/dbdmysql.dir/src/drivers/mysql.cc.i
.PHONY : src/drivers/mysql.cc.i

src/drivers/mysql.s: src/drivers/mysql.cc.s
.PHONY : src/drivers/mysql.s

# target to generate assembly for a file
src/drivers/mysql.cc.s:
	$(MAKE) -f CMakeFiles/dbdmysql.dir/build.make CMakeFiles/dbdmysql.dir/src/drivers/mysql.cc.s
.PHONY : src/drivers/mysql.cc.s

src/drivers/pg.o: src/drivers/pg.cc.o
.PHONY : src/drivers/pg.o

# target to build an object file
src/drivers/pg.cc.o:
	$(MAKE) -f CMakeFiles/dbdpg.dir/build.make CMakeFiles/dbdpg.dir/src/drivers/pg.cc.o
.PHONY : src/drivers/pg.cc.o

src/drivers/pg.i: src/drivers/pg.cc.i
.PHONY : src/drivers/pg.i

# target to preprocess a source file
src/drivers/pg.cc.i:
	$(MAKE) -f CMakeFiles/dbdpg.dir/build.make CMakeFiles/dbdpg.dir/src/drivers/pg.cc.i
.PHONY : src/drivers/pg.cc.i

src/drivers/pg.s: src/drivers/pg.cc.s
.PHONY : src/drivers/pg.s

# target to generate assembly for a file
src/drivers/pg.cc.s:
	$(MAKE) -f CMakeFiles/dbdpg.dir/build.make CMakeFiles/dbdpg.dir/src/drivers/pg.cc.s
.PHONY : src/drivers/pg.cc.s

src/error.o: src/error.cc.o
.PHONY : src/error.o

# target to build an object file
src/error.cc.o:
	$(MAKE) -f CMakeFiles/dbic++.dir/build.make CMakeFiles/dbic++.dir/src/error.cc.o
.PHONY : src/error.cc.o

src/error.i: src/error.cc.i
.PHONY : src/error.i

# target to preprocess a source file
src/error.cc.i:
	$(MAKE) -f CMakeFiles/dbic++.dir/build.make CMakeFiles/dbic++.dir/src/error.cc.i
.PHONY : src/error.cc.i

src/error.s: src/error.cc.s
.PHONY : src/error.s

# target to generate assembly for a file
src/error.cc.s:
	$(MAKE) -f CMakeFiles/dbic++.dir/build.make CMakeFiles/dbic++.dir/src/error.cc.s
.PHONY : src/error.cc.s

src/example.o: src/example.cc.o
.PHONY : src/example.o

# target to build an object file
src/example.cc.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/example.cc.o
.PHONY : src/example.cc.o

src/example.i: src/example.cc.i
.PHONY : src/example.i

# target to preprocess a source file
src/example.cc.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/example.cc.i
.PHONY : src/example.cc.i

src/example.s: src/example.cc.s
.PHONY : src/example.s

# target to generate assembly for a file
src/example.cc.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/example.cc.s
.PHONY : src/example.cc.s

src/param.o: src/param.cc.o
.PHONY : src/param.o

# target to build an object file
src/param.cc.o:
	$(MAKE) -f CMakeFiles/dbic++.dir/build.make CMakeFiles/dbic++.dir/src/param.cc.o
.PHONY : src/param.cc.o

src/param.i: src/param.cc.i
.PHONY : src/param.i

# target to preprocess a source file
src/param.cc.i:
	$(MAKE) -f CMakeFiles/dbic++.dir/build.make CMakeFiles/dbic++.dir/src/param.cc.i
.PHONY : src/param.cc.i

src/param.s: src/param.cc.s
.PHONY : src/param.s

# target to generate assembly for a file
src/param.cc.s:
	$(MAKE) -f CMakeFiles/dbic++.dir/build.make CMakeFiles/dbic++.dir/src/param.cc.s
.PHONY : src/param.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... dbdmysql"
	@echo "... dbdpg"
	@echo "... dbic++"
	@echo "... edit_cache"
	@echo "... example"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... src/container.o"
	@echo "... src/container.i"
	@echo "... src/container.s"
	@echo "... src/dbic++.o"
	@echo "... src/dbic++.i"
	@echo "... src/dbic++.s"
	@echo "... src/drivers/mysql.o"
	@echo "... src/drivers/mysql.i"
	@echo "... src/drivers/mysql.s"
	@echo "... src/drivers/pg.o"
	@echo "... src/drivers/pg.i"
	@echo "... src/drivers/pg.s"
	@echo "... src/error.o"
	@echo "... src/error.i"
	@echo "... src/error.s"
	@echo "... src/example.o"
	@echo "... src/example.i"
	@echo "... src/example.s"
	@echo "... src/param.o"
	@echo "... src/param.i"
	@echo "... src/param.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

